// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/getConnections.tsx";
import * as $1 from "./routes/api/handleConnectionSave.ts";
import * as $2 from "./routes/api/handleModelSave.ts";
import * as $3 from "./routes/api/handleQueryRun.ts";
import * as $4 from "./routes/api/handleQuerySave.ts";
import * as $5 from "./routes/api/writeUriToFile.ts";
import * as $6 from "./routes/connections.tsx";
import * as $7 from "./routes/explorer.tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/migrations.tsx";
import * as $$0 from "./islands/Connections.tsx";
import * as $$1 from "./islands/Console.tsx";
import * as $$2 from "./islands/Migrations.tsx";

const manifest = {
  routes: {
    "./routes/api/getConnections.tsx": $0,
    "./routes/api/handleConnectionSave.ts": $1,
    "./routes/api/handleModelSave.ts": $2,
    "./routes/api/handleQueryRun.ts": $3,
    "./routes/api/handleQuerySave.ts": $4,
    "./routes/api/writeUriToFile.ts": $5,
    "./routes/connections.tsx": $6,
    "./routes/explorer.tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/migrations.tsx": $9,
  },
  islands: {
    "./islands/Connections.tsx": $$0,
    "./islands/Console.tsx": $$1,
    "./islands/Migrations.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
