// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/handleQueryRun.tsx";
import * as $1 from "./routes/api/handleQuerySave.tsx";
import * as $2 from "./routes/explorer.tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/Console.tsx";

const manifest = {
  routes: {
    "./routes/api/handleQueryRun.tsx": $0,
    "./routes/api/handleQuerySave.tsx": $1,
    "./routes/explorer.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/Console.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
